const ROUTECONSTANTS={
    REGISTER:'REGISTER',
    LOGIN:'LOGIN',
    HOME:'HOME',
    VERIFYEMAIL:'VERIFYEMAIL',
    LOGOUT:'LOGOUT',
    FOLLOW:'FOLLOW',
    TWEETS:'TWEETS',
    UNFOLLOW:'UNFOLLOW',
    EDITDETAILS:'EDITDETAILS'
};
const ERRORS={
  INVALID_TOKEN:'INVALID TOKEN',
    NOT_AUTHORIZED:'NOT AUTHORIZED',
    ALREADY_FOLLOWED:'ALREADY FOLLOWED',
    ALREADY_UNFOLLOWED:'ALREADY UNFOLLOWED',
    INVALID_USERNAME:'INVALID USERNAME',
    USER_NOT_VERIFIED:'USER NOT VERIFIED',
    INVALID_CREDENTIALS:'INVALID_CREDENTIALS',
    SOMETHING_WENT_WRONG:'SOMETHING WENT WRONG,PLEASE TRY AGAIN'
};

const KEYS={
    PRIVATEKEY:'BbZJjyoXAdr8BUZuiKKARWimKfrSmQ6fv8kZ7OFfc',
    REGISTERPRIVATEKEY:'37LvDSm4XvjYOh9Y'
};

module.exports={
    KEYS:KEYS,
    ROUTECONSTANTS:ROUTECONSTANTS,
    ERRORS:ERRORS,
};