const SORTCONSTANTS={
    QUICKSORT:'quicksort',
    COUNTINGSORT:'countingsort'
}

const OPERATECONSTANTS={
    UNIQUE:'unique',
    REVERSE:'reverse',
    ODDELEMENT:'index of odd element'
}
const CRUDDBCONSTANTS={
    PULLELEMENT:'PULLEMENT',
    PUSHELEMENT:'PUSHELEMENT',
    INSERTELEMENT:'INSERTELEMENT',
    SORT:'SORT'
}

const KEYS={
    PRIVATEKEY:'BbZJjyoXAdr8BUZuiKKARWimKfrSmQ6fv8kZ7OFfc',
    REGISTERPRIVATEKEY:'37LvDSm4XvjYOh9Y'
}


module.exports={
    KEYS:KEYS,
    SORTCONSTANTS:SORTCONSTANTS,
    OPERATECONSTANTS:OPERATECONSTANTS,
    CRUDDBCONSTANTS:CRUDDBCONSTANTS
}